// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx9pMB1itKlxrbyL3HkSdMvtUuY-AXjCA',
    appId: '1:862265403047:web:4e20d5142faa90d3bd9d82',
    messagingSenderId: '862265403047',
    projectId: 'cage-2025',
    authDomain: 'cage-2025.firebaseapp.com',
    storageBucket: 'cage-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoTcuHJdf44cHFlIZaP43mdTiBZT97Lfs',
    appId: '1:862265403047:android:dff27272bb1b365ebd9d82',
    messagingSenderId: '862265403047',
    projectId: 'cage-2025',
    storageBucket: 'cage-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPfgvqPXk1m5Za4eYBDWe7BkOeEQEiR1U',
    appId: '1:862265403047:ios:c493e2a21b4d436dbd9d82',
    messagingSenderId: '862265403047',
    projectId: 'cage-2025',
    storageBucket: 'cage-2025.firebasestorage.app',
    iosBundleId: 'com.craz.cage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPfgvqPXk1m5Za4eYBDWe7BkOeEQEiR1U',
    appId: '1:862265403047:ios:5527bfd6ae6cc6f4bd9d82',
    messagingSenderId: '862265403047',
    projectId: 'cage-2025',
    storageBucket: 'cage-2025.firebasestorage.app',
    iosBundleId: 'com.test1.cage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBx9pMB1itKlxrbyL3HkSdMvtUuY-AXjCA',
    appId: '1:862265403047:web:3fa15a933eae366bbd9d82',
    messagingSenderId: '862265403047',
    projectId: 'cage-2025',
    authDomain: 'cage-2025.firebaseapp.com',
    storageBucket: 'cage-2025.firebasestorage.app',
  );
}
