// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhsS1E8LmsXho94nIxqMtMTzSkA5xs5xs',
    appId: '1:755745368604:web:24d96c139253e939e50dd9',
    messagingSenderId: '755745368604',
    projectId: 'cageconnectapp',
    authDomain: 'cageconnectapp.firebaseapp.com',
    storageBucket: 'cageconnectapp.firebasestorage.app',
    measurementId: 'G-PN81C9J6LQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD99N39VJXgSmWYtmtk7SfShORNDWzyefc',
    appId: '1:755745368604:android:9c6f8a672920eb81e50dd9',
    messagingSenderId: '755745368604',
    projectId: 'cageconnectapp',
    storageBucket: 'cageconnectapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABPIl5wABNvbWRt2U5Hl9r45KtZ4K0kx4',
    appId: '1:755745368604:ios:5d3aa9bcf2acfbd0e50dd9',
    messagingSenderId: '755745368604',
    projectId: 'cageconnectapp',
    storageBucket: 'cageconnectapp.firebasestorage.app',
    iosBundleId: 'com.craz.cage',
  );

}